name: Triage

on:
  workflow_call:
    inputs:
      number_of_project:
        required: true
        type: string
    secrets:
      github-token:
        required: true

jobs:
  add-ticket-to-project:
    name: Add ticket to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/maliput/projects/${{ inputs.number_of_project }}
          github-token: ${{ secrets.github-token }}
